# Generated by Django 4.1 on 2023-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="genre",
            field=models.CharField(
                choices=[
                    ("FA", "Fantasy"),
                    ("AD", "Adventure"),
                    ("RO", "Romance"),
                    ("CO", "Contemporary"),
                    ("DY", "Dystopian"),
                    ("MY", "Mystery"),
                    ("HO", "Horror"),
                    ("TH", "Thriller"),
                    ("PA", "Paranormal"),
                    ("HF", "Historical Fiction"),
                    ("SF", "Science Fiction"),
                    ("CH", "Children's"),
                    ("OT", "Other"),
                ],
                max_length=25,
            ),
        ),
    ]
