# Generated by Django 4.1 on 2023-04-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_genre_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("FA", "Fantasy"),
                    ("AD", "Adventure"),
                    ("RO", "Romance"),
                    ("CO", "Contemporary"),
                    ("DY", "Dystopian"),
                    ("MY", "Mystery"),
                    ("HO", "Horror"),
                    ("TH", "Thriller"),
                    ("PA", "Paranormal"),
                    ("HF", "Historical Fiction"),
                    ("SF", "Science Fiction"),
                    ("CH", "Children's"),
                    ("OT", "Other"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(name="Author",),
        migrations.DeleteModel(name="Genre",),
        migrations.DeleteModel(name="Language",),
    ]
