# Generated by Django 4.1 on 2023-04-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_author_alter_book_genre_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookinstance", name="due_back",),
    ]
