# Generated by Django 4.1 on 2023-04-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_remove_bookinstance_due_back"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="borrow_the_book",
            field=models.BooleanField(default=False),
        ),
    ]
