# Generated by Django 4.1 on 2023-04-07 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_bookinstance_borrow_the_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.PositiveBigIntegerField(
                max_length=13,
                unique=True,
                validators=[django.core.validators.MaxValueValidator(9999999999999)],
            ),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="availability",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")], default="Y", max_length=3
            ),
        ),
    ]
